# Generated by Django 2.2.3 on 2019-07-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='default.jpg', upload_to='profile_pic'),
        ),
    ]
