# Generated by Django 2.2.3 on 2019-07-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Customer'), (2, 'Staff'), (3, 'Admin')], default=1),
        ),
    ]
